# Generated by Django 4.0.8 on 2022-12-03 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('printable_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',)},
        ),
        migrations.AddField(
            model_name='category',
            name='soruce',
            field=models.URLField(default='https://iheartcraftythings.com'),
        ),
    ]
