# Generated by Django 4.0.8 on 2022-12-03 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('printable_books', '0002_alter_category_options_category_soruce'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='soruce',
            new_name='source',
        ),
    ]
